<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LP1124" name="com.br.inmetrics.phpSuppliers.Testes.Test_phpSuppliers_Cadastro" tests="1" failures="1" timestamp="30 ago 2019 10:47:13 GMT" time="34.150" errors="0">
  <testcase name="login_admin" time="34.150" classname="com.br.inmetrics.phpSuppliers.Testes.Test_phpSuppliers_Cadastro">
    <failure type="java.lang.AssertionError" message="Deu Ruim">
      <![CDATA[java.lang.AssertionError: Deu Ruim
at org.testng.Assert.fail(Assert.java:85)
at com.br.inmetrics.phpSuppliers.Testes.Test_phpSuppliers_Cadastro.login_admin(Test_phpSuppliers_Cadastro.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
at br.com.santander.frm.bdd.Gherkin.executeScenario_(Gherkin.java:333)
at com.br.inmetrics.phpSuppliers.Testes.Test_phpSuppliers_Cadastro.login_admin(Test_phpSuppliers_Cadastro.java:36)
... 25 more
]]>
    </failure>
  </testcase> <!-- login_admin -->
</testsuite> <!-- com.br.inmetrics.phpSuppliers.Testes.Test_phpSuppliers_Cadastro -->
