<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="686" started-at="2019-08-30T13:04:32Z" finished-at="2019-08-30T13:04:32Z">
    <groups>
      <group name="Login">
        <method signature="LoginTest.login_admin()[pri:1, instance:com.br.inmetrics.phpSuppliers.Testes.LoginTest@7d3a22a9]" name="login_admin" class="com.br.inmetrics.phpSuppliers.Testes.LoginTest"/>
      </group> <!-- Login -->
    </groups>
    <test name="Default test" duration-ms="686" started-at="2019-08-30T13:04:32Z" finished-at="2019-08-30T13:04:32Z">
      <class name="com.br.inmetrics.phpSuppliers.Testes.LoginTest">
        <test-method status="FAIL" signature="setup(java.lang.reflect.Method, org.testng.ITestContext)[pri:0, instance:com.br.inmetrics.phpSuppliers.Testes.LoginTest@7d3a22a9]" name="setup" is-config="true" duration-ms="307" started-at="2019-08-30T13:04:32Z" finished-at="2019-08-30T13:04:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.br.inmetrics.phpSuppliers.Testes.LoginTest.login_admin()]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@41a0aa7d]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Setup error.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Setup error.
at org.testng.Assert.fail(Assert.java:85)
at br.com.santander.frm.base.TestBase.setup(TestBase.java:45)
at com.br.inmetrics.phpSuppliers.Testes.LoginTest.setup(LoginTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: br.com.santander.frm.exceptions.GherkinDuplicateStepException: Duplicated step [Estiver na pagina de login] was found.
at br.com.santander.frm.helpers.GherkinHelper.getSteps(GherkinHelper.java:164)
at br.com.santander.frm.bdd.Gherkin.<init>(Gherkin.java:78)
at br.com.santander.frm.bdd.Gherkin.createOrInstance(Gherkin.java:102)
at br.com.santander.frm.base.DefaultBaseController.initializeController(DefaultBaseController.java:72)
at br.com.santander.frm.helpers.TestBaseHelper.doBefore(TestBaseHelper.java:148)
at br.com.santander.frm.base.TestBase.setup(TestBase.java:41)
... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="login_admin()[pri:1, instance:com.br.inmetrics.phpSuppliers.Testes.LoginTest@7d3a22a9]" name="login_admin" duration-ms="0" started-at="2019-08-30T13:04:32Z" finished-at="2019-08-30T13:04:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Setup error.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Setup error.
at org.testng.Assert.fail(Assert.java:85)
at br.com.santander.frm.base.TestBase.setup(TestBase.java:45)
at com.br.inmetrics.phpSuppliers.Testes.LoginTest.setup(LoginTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: br.com.santander.frm.exceptions.GherkinDuplicateStepException: Duplicated step [Estiver na pagina de login] was found.
at br.com.santander.frm.helpers.GherkinHelper.getSteps(GherkinHelper.java:164)
at br.com.santander.frm.bdd.Gherkin.<init>(Gherkin.java:78)
at br.com.santander.frm.bdd.Gherkin.createOrInstance(Gherkin.java:102)
at br.com.santander.frm.base.DefaultBaseController.initializeController(DefaultBaseController.java:72)
at br.com.santander.frm.helpers.TestBaseHelper.doBefore(TestBaseHelper.java:148)
at br.com.santander.frm.base.TestBase.setup(TestBase.java:41)
... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_admin -->
        <test-method status="PASS" signature="teardown(java.lang.reflect.Method, org.testng.ITestContext, org.testng.ITestResult)[pri:0, instance:com.br.inmetrics.phpSuppliers.Testes.LoginTest@7d3a22a9]" name="teardown" is-config="true" duration-ms="42" started-at="2019-08-30T13:04:32Z" finished-at="2019-08-30T13:04:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.br.inmetrics.phpSuppliers.Testes.LoginTest.login_admin()]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@41a0aa7d]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest.login_admin()[pri:1, instance:com.br.inmetrics.phpSuppliers.Testes.LoginTest@7d3a22a9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.br.inmetrics.phpSuppliers.Testes.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
